### ISSUE TITLE
导入模板报错

### ISSUE THREAD

**Issue by hippocampi** [0312birdzhang/Template-SNMP-A10#1]
Cannot find value map "A10 HA状态" used for item "Local HA Group状态" on "Template SNMP A10".

zabbix版本2.4.4

**Comment by 0312birdzhang** [comment]
已修复
先导入那两个表的数据(我的模板里面用到了valuemap里面的东西)
建议用那个新的模板

**Comment by 0312birdzhang** [comment]
@hippocampi 用mibbrowser载入A10的mib文件就可以制作了.我做的只是我们需要一部分,还有很多没有加进去.

**Comment by hippocampi** [comment]
感谢
